src/routes.py
import calendar
import random
from datetime import datetime, timedelta

from dateutil.relativedelta import relativedelta
from flask import render_template, flash, redirect, url_for, Blueprint, request, jsonify, Response, send_file, session
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.utils import secure_filename
from src.config import UPLOAD_FOLDER, EMAIL_KEY
from src.forms import LoginForm, MeterForm, UploadForm, UserForm, EditAccountForm, \
    UserNotesForm, UserOverviewForm, MessageForm, AssignMeterToSuperuserForm, AssignMeterToUserForm, EditUserForm, \
    MONTHS_PL
from src.models import User, db, Meter, MeterReading, get_all_users, Message, Address, MeterEditHistory, UserReportMonth
import os
from src.utils import process_csv_water, process_csv_heat, admin_required, is_valid_link, process_csv_events, \
    superuser_required, create_report_data, generate_random_password, remove_duplicate_readings

main_routes = Blueprint('main_routes', __name__)
admin_routes = Blueprint('admin_routes', __name__)
superuser_routes = Blueprint('superuser_routes', __name__)
user_routes = Blueprint('user_routes', __name__)


@main_routes.route('/')
def welcome():
    if current_user.is_authenticated == True:
        return redirect(url_for("main_routes.home"))
    else:
        return redirect(url_for("main_routes.login"))


@main_routes.route('/home')
def home():
    if current_user.is_authenticated:
        if current_user.is_admin:
            return redirect(url_for("admin_routes.admin_panel"))
        if current_user.is_superuser:
            return redirect(url_for("main_routes.superuser_panel"))
        user = current_user
        assigned_meters = user.meters
        return render_template('home.html', assigned_meters=assigned_meters)
    return redirect(url_for('main_routes.login'))


@main_routes.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_routes.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user is None or not user.check_password(form.password.data):
            flash('Nieprawidłowy email lub hasło.', 'danger')
            return redirect(url_for('main_routes.login'))
        if not user.is_active:
            flash('Konto zostało dezaktywowane, skontaktuj się z administracją.', 'warning')
            return redirect(url_for('main_routes.login'))

        login_user(user)
        flash('Zalogowano pomyślnie.', 'success')
        return redirect(url_for('main_routes.home'))

    return render_template('login.html', form=form)


@main_routes.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main_routes.home'))


@admin_routes.route('/upload_csv', methods=['GET', 'POST'])
@admin_required
def upload_csv():
    form = UploadForm()
    if form.validate_on_submit():
        device_type = form.device_type.data
        file = form.file.data
        file_path = os.path.join(UPLOAD_FOLDER, secure_filename(file.filename))
        file.save(file_path)

        if device_type == 'water':
            result_message = process_csv_water(file_path)
            if "Problem" in result_message:
                flash(result_message, 'danger')
                return redirect(url_for('main_routes.home'))
        elif device_type == 'heat':
            result_message = process_csv_heat(file_path)
            if "Problem" in result_message:
                flash(result_message, 'danger')
                return redirect(url_for('admin_routes.upload_csv'))
        elif device_type == 'events_water':
            # Nowy kod dla plików zdarzeń
            process_csv_events(file_path, 'water')
        elif device_type == 'events_heat':
            # Nowy kod dla plików zdarzeń
            process_csv_events(file_path, 'heat')

        flash('Plik CSV przesłany pomyślnie.')
        if os.path.exists(file_path):
            os.remove(file_path)
        return redirect(url_for('main_routes.home'))

    return render_template('upload_csv.html', form=form)


@user_routes.route('/user_meters')
@login_required
def user_meters():
    user_meters = Meter.query.filter_by(user_id=current_user.id).all()
    return render_template('user_meters.html', user_meters=user_meters)


@main_routes.route('/meter_details/<int:meter_id>', methods=['GET', 'POST'])
@login_required
def meter_details(meter_id):
    meter = Meter.query.get_or_404(meter_id)
    user = meter.user
    events = meter.events
    # Sprawdzenie, czy bieżący użytkownik to właściciel licznika, administrator, lub superużytkownik z dostępem do tego licznika
    if current_user != meter.user and not current_user.is_admin and not (
            current_user.is_superuser and meter.superuser_id == current_user.id):
        flash('Brak uprawnień do wyświetlenia tych szczegółów.', 'danger')
        return redirect(url_for('main_routes.home'))

    readings = MeterReading.query.filter_by(meter_id=meter.id).all()
    readings_list = [{"date": reading.date, "reading": reading.reading} for reading in readings]
    if user:
        user_months = {user.id: [month.month for month in user.report_months]}
    if current_user.is_superuser:
        for assigned_user in current_user.assigned_users:
            user_months[assigned_user.id] = [month.month for month in assigned_user.report_months]

    if not current_user.is_admin:
        user_accessible_months = user_months.get(meter.user.id, [])
        readings_list = [reading for reading in readings_list if reading['date'].month in user_accessible_months]
    return render_template('meter_details.html', meter=meter, readings=readings_list, user=user, events=events)


@main_routes.route('/delete_meter/<int:meter_id>', methods=['POST'])
@admin_required
def delete_meter(meter_id):
    meter = Meter.query.get_or_404(meter_id)
    db.session.delete(meter)
    db.session.commit()
    flash('Licznik został usunięty.', 'success')
    return redirect(url_for('admin_routes.admin_panel'))


@main_routes.route('/clear_readings/<int:meter_id>', methods=['POST'])
@admin_required
def clear_readings(meter_id):
    meter = Meter.query.get_or_404(meter_id)
    meter.readings.delete()
    db.session.commit()
    flash('Odczyty licznika zostały wyczyszczone.', 'success')
    return redirect(url_for('main_routes.meter_details', meter_id=meter_id))


@main_routes.route('/update_meter_name/<int:meter_id>', methods=['POST'])
@login_required
def update_meter_name(meter_id):
    meter = Meter.query.get_or_404(meter_id)
    if current_user == meter.user:
        new_name = request.form.get('new_name')
        if new_name:
            meter.name = new_name
            db.session.commit()
            flash('Pomyślnie zmieniono nazwę.', 'success')
        else:
            flash('Nazwa nie może być pusta.', 'danger')
    else:
        flash('Nie masz uprawnień do zmiany nazwy licznika.', 'danger')
    return redirect(url_for('main_routes.meter_details', meter_id=meter.id))


@main_routes.route('/update_meter_address/<int:meter_id>', methods=['POST'])
@login_required
def update_meter_address(meter_id):
    meter = Meter.query.get_or_404(meter_id)
    if request.method == 'POST':
        city = request.form.get('city')
        street = request.form.get('street')
        building_number = request.form.get('building_number')
        apartment_number = request.form.get('apartment_number')
        postal_code = request.form.get('postal_code')
        edit_details = ""

        if meter.address:
            address = meter.address
            # Sprawdź, które pola zostały zmienione i zapisz szczegóły
            if address.city != city:
                edit_details += f"City changed from {address.city} to {city}. "
            if address.street != street:
                edit_details += f"Street changed from {address.street} to {street}. "
            if address.building_number != building_number:
                edit_details += f"Building number changed from {address.building_number} to {building_number}. "
            if address.apartment_number != apartment_number:
                edit_details += f"Apartment number changed from {address.apartment_number} to {apartment_number}. "
            if address.postal_code != postal_code:
                edit_details += f"Postal code changed from {address.postal_code} to {postal_code}. "

            address.city = city
            address.street = street
            address.building_number = building_number
            address.apartment_number = apartment_number
            address.postal_code = postal_code
        else:
            address = Address(city=city, street=street, building_number=building_number,
                              apartment_number=apartment_number, postal_code=postal_code)
            meter.address = address
            edit_details = f"Address added.{address.city}, {address.street}, {address.building_number}, {address.apartment}"
            db.session.add(address)

        # Dodaj wpis do historii edycji
        if edit_details:
            new_history_entry = MeterEditHistory(meter_id=meter_id, user_id=current_user.id,
                                                 edit_type='Change Address', edit_details=edit_details)
            db.session.add(new_history_entry)

        db.session.commit()
    return redirect(url_for('main_routes.meter_details', meter_id=meter.id))


@admin_routes.route('/admin_panel', methods=['GET'])
@admin_required  # Dodaj dekorator, aby wymagać uprawnień administratora
def admin_panel():
    user_form = UserForm()

    if user_form.validate_on_submit():
        user = User(email=user_form.email.data)
        user.set_password(user_form.password.data)
        if user_form.is_admin.data:
            user.is_admin = True
        if user_form.is_superuser.data:
            user.is_superuser = True
        db.session.add(user)

templates/add_meter.html
{% extends 'base.html' %}

{% block content %}
<div class="center-box">
    <h2>Add Meter</h2>
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.radio_number.label(class="form-field") }}
            {{ form.radio_number(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.type.label(class="form-field") }}
            {{ form.type(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.user_id.label(class="form-field") }}
            {{ form.user_id(class="form-control") }}
        </div>
        <button type="submit" class="btn btn-primary">Add Meter</button>
    </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <title>Zdalny Odczyt</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
    <link rel="icon" href="{{ url_for('static', filename='img/logo.png') }}" type="image/x-icon">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='GeneralStyles.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='Layout.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='ButtonsAndForms.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='MediaQueries.css')}}">

    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

    {% block extra_css %}

    {% endblock extra_css %}

</head>


<body>
<script>
function adjustMargin() {
    var navbarHeight = document.querySelector('.navbar').offsetHeight;
    var centerBox = document.querySelector('.center-box');
    centerBox.style.marginTop = navbarHeight + 'px';
}

// Wywołaj funkcję przy ładowaniu strony
window.onload = adjustMargin;

// Wywołaj funkcję przy zmianie rozmiaru okna
window.onresize = adjustMargin;
</script>

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('main_routes.home') }}"><img src="{{ url_for('static', filename='img/Zdalny_Odczyt_RGB.png') }}" alt="Logo" class="logo">
        </a>
    {% if current_user.is_authenticated %}
    <p class="navbar-brand">Witaj, {{ current_user.email.split('@')[0] }}!</p>
    {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('main_routes.home') }}">  <span class="sr-only">(current)</span></a>
                </li>

            </ul>
            <div class="form-inline my-2 my-lg-0">
                {% if current_user.is_authenticated %}
                {% if current_user.is_admin %}
                <p><a href="{{ url_for('admin_routes.upload_csv') }} " class="btn btn-warning">Prześlij plik</a></p>
                    <p><a href="{{ url_for('main_routes.generate_report') }} " class="btn btn-warning">Generuj raport</a></p>
                    <p><a href="{{ url_for('admin_routes.admin_panel') }} " class="btn btn-warning">Panel Administratora</a></p>
                    <p><a href="{{ url_for('main_routes.messages') }}" class="btn btn-warning">Wyślij wiadodmość</a></p>
                {% endif %}
                 {% if current_user.is_superuser %}
                     <p><a href="{{ url_for('main_routes.superuser_panel') }} " class="btn btn-warning">Panel Zarządzania</a></p>
                     <p><a href="{{ url_for('main_routes.generate_report') }} " class="btn btn-warning">Generuj raport</a></p>
                 {% endif %}
                <p class="navbar-brand">     </p>

                    {% if not current_user.is_admin %}
                    <p><a href="{{ url_for('main_routes.messages') }} " class="btn btn-warning">Wiadomości
                    {% if current_user.unread_messages > 0 %}
      <span class="badge badge-danger">{{ current_user.unread_messages }}</span>
    {% endif %}
                    {% endif %}
                    </a></p>
                    <p><a href="{{ url_for('main_routes.edit_account') }}" class="btn btn-warning">Edytuj profil</a></p>
                    <p><a href="{{ url_for('main_routes.logout') }} " class="btn btn-warning">Wyloguj</a></p>
                {% else %}

                    <a href="{{ url_for('main_routes.login') }}" class="btn btn-warning">Login</a>
                {% endif %}


            </div>
        </div>




</nav>

<div class="center-box">
{% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-info">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
    <br>
    {% block content %}


    {% endblock content %}
</div>



<footer class="footer no-print">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h3 style="color: #f9f9f9">Kontakt</h3>
                <p style="color: #f9f9f9">Telefon: 608 25 88 77</p>
                <p style="color: #f9f9f9">Nawiąż współpracę: mw@zdalnyodczyt.com</p>
                <p style="color: #f9f9f9">Wsparcie techniczne: wojciech.adamski@smartbits.pl</p>
            </div>
            <div class="col-md-6">
                <h3 style="color: #f9f9f9">Linki</h3>
                <ul>
                    <li style="color: #f9f9f9"><a href="#" style="color: #f9f9f9">Polityka prywatności</a></li>
                    <li style="color: #f9f9f9"><a href="#" style="color: #f9f9f9">Warunki użytkowania</a></li>
                    <li style="color: #f9f9f9"><a href="#" style="color: #f9f9f9">Regulamin</a></li>
                </ul>
            </div>
        </div>
    </div>
    <center style="color: #f9f9f9"> <a href="https://linkedin.com/in/wojciech-adamski-b1a3b1a9/ " class="signature" target="_blank"> Wojciech Adamski</a>   2024</center>
</footer>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>


</body>
</html>

templates/edit_account.html
{% extends 'base.html' %}
{% block extra_css %}
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='ButtonsAndForms.css')}}">
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='MediaQueries.css')}}">

{% endblock extra_css %}


{% block content %}
    <a href="{{ url_for('main_routes.home') }} " class="btn btn-secondary no-print">Powrót</a>
  <h1>Edytuj profil</h1>
    <h3>Użytkownik: {{ user_email }}</h3>
  <form method="POST" action="{{ url_for('main_routes.edit_account') }}" style="width: 400px">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.current_password.label }}
      {{ form.current_password(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.new_password.label }}
      {{ form.new_password(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.confirm_password.label }}
      {{ form.confirm_password(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>
{% endblock %}

templates/edit_meter.html
{% extends "base.html" %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='edit_meter_styles.css')}}">
{% endblock extra_css %}

{% block content %}
<div class="edit-meter-container ">
    <form method="post" action="{{ url_for('admin_routes.edit_meter', meter_id=meter.id) }}">
        <div class="form-group">
            <label for="new_radio_number">Nowy numer radiowy:</label>
            <input type="text" id="new_radio_number" name="new_radio_number" class="form-control" value="{{ meter.radio_number }}">
        </div>
        <button type="submit" class="btn btn-primary">Zapisz zmiany</button>
    </form>

    <h3>Odczyty</h3>
<div class="table-responsive">
    <form method="post" action="{{ url_for('main_routes.edit_meter', meter_id=meter.id) }}">
        <table>
        <tr>
            <th>Zaznacz</th>
            <th>Data</th>
            <th>Odczyt</th>
            <th>Edytuj odczyt</th>
        </tr>
        {% for reading in readings %}
        <tr>
            <td><input type="checkbox" name="reading_ids" value="{{ reading.id }}"></td>
            <td>{{ reading.date }}</td>
            <td>{{ reading.reading }}</td>
            <td><input type="text" name="reading_value_{{ reading.id }}" value="{{ reading.reading }}"></td>
        </tr>
        {% endfor %}
    </table>
        <button type="submit" class="btn btn-primary">Zapisz zmiany</button>
    </form>
</div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block extra_css %}
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='UserList.css')}}">

{% endblock extra_css %}
{% block content %}
    <h2>Witaj, {{ current_user.email.split('@')[0] }}!</h2>
    <div class="left-box">
    <h3>Twoje liczniki:</h3>
    <input type="text" id="search-input" placeholder="Wyszukaj">
    <ul id="assigned-meters-list" class="user-list limited-list" style="width: 250px" id="meter-list">

        {% for meter in assigned_meters %}
            <li class="meter-item assigned-meter"><a href="{{ url_for('main_routes.meter_details', meter_id=meter.id) }}">
                 {% if meter.name %}
                        {{ meter.name }} ({{ meter.radio_number }})
                    {% else %}
                        {{ meter.radio_number }}
                    {% endif %}
            </a></li>
        {% endfor %}
    </ul>

    </div>

    <div class="right-box">
    {% block summary %}

    {% endblock summary %}

    </div>

     <script>
        const searchInput = document.getElementById('search-input');
        const assignedMetersList = document.getElementById('assigned-meters-list');

        searchInput.addEventListener('input', function() {
            const searchQuery = searchInput.value.toLowerCase();
            const assignedMeters = document.querySelectorAll('.assigned-meter');

            assignedMeters.forEach(function(meter) {
                const meterText = meter.textContent.toLowerCase();
                if (meterText.includes(searchQuery)) {
                    meter.style.display = 'block';
                } else {
                    meter.style.display = 'none';
                }
            });
        });
    </script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block extra_css %}
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='ButtonsAndForms.css')}}">
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='MediaQueries.css')}}">

{% endblock extra_css %}
{% block content %}
    <h1>Logowanie</h1>
    <div class="right-box">
    <form method="POST" action="{{ url_for('main_routes.login') }}" style="max-width: 300px">
  {{ form.hidden_tag() }}
  <div class="form-group" >
    {{ form.email.label }}
    {{ form.email(class="form-control") }}
  </div>
  <div class="form-group">
    {{ form.password.label }}
    {{ form.password(class="form-control") }}
  </div>
  <div class="form-group form-check">
    {{ form.remember_me(class="form-check-input") }}
    {{ form.remember_me.label(class="form-check-label") }}  <!-- Dodaj pole remember_me -->
  </div>
  <div class="form-group">
    {{ form.submit(class="btn btn-primary") }}
  </div>
</form>
    <p>Nie masz konta? Skontaktuj się z firmą <a href="https://smartbits.pl/">Smartbits</a></p>
</div>
{% endblock content %}

templates/meter_history.html
{% extends 'base.html' %}
{% block extra_css %}
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='meter_history.css')}}">
{% endblock extra_css %}
{% block content %}
    <button class="btn btn-secondary no-print" onclick="goBack()">Powrót</button>
<div class="edit-container">
    <h2>Historia Edycji Licznika: {{ meter.radio_number }}</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Data i czas</th>
                <th>Typ edycji</th>
                <th>Szczegóły</th>
            </tr>
        </thead>
        <tbody>
            {% for entry in history %}
            <tr>
                <td>{{ entry.timestamp.strftime('%Y-%m-%d %H:%M') }}</td>
                <td>{{ entry.edit_type }}</td>
                <td>{{ entry.edit_details }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
    <script>
    function goBack() {
            window.history.back();
        }

    </script>
{% endblock %}

templates/report_issue.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-4">
    <h2 class="mb-4 text-center">Zgłoś problem z odczytem</h2>
    <div class="card">
        <div class="card-body">
            <form method="post">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.meter_reading.label(class="form-label") }}
                    {{ form.meter_reading(class="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.suggested_reading.label(class="form-label") }}
                    {{ form.suggested_reading(class="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.description.label(class="form-label") }}
                    {{ form.description(class="form-control") }}
                </div>
                <button type="submit" class="btn btn-danger">Zgłoś</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/superuser_panel.html
{% extends 'base.html' %}

{% block extra_css %}
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='UserList.css')}}">
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='ButtonsAndForms.css')}}">

{% endblock extra_css %}

{% block content %}
    <h2>Panel Administratora zasobów</h2>
    <div class="content-box">
        <div class="left-box" style="width: 25%">
            <h3>Lista Twoich zasobów</h3>
            <input type="text" id="search-user-input" placeholder="Wyszukaj użytkownika" class="search-bar">
            <ul class="user-list limited-list" style="width: 320px" id="user-list">
                {% for user in users %}
                    <li class="user-item">
                        <a href="{{ url_for('main_routes.superuser_user_overview', user_id=user.id) }}">{{ user.email }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="right-box user-overview-container">
        {% block user %}
        {% endblock user %}

        {% block instructions %}
        <h3>Instrukcja obsługi strony</h3>
        <p>Tutaj znajdziesz opis funkcji dostępnych w pasku nawigacyjnym:</p>
        <ul class="instructions-list">
            <li><a href="{{ url_for('main_routes.generate_report') }}" class="btn btn-warning">Generuj raport</a> - pozwala na generowanie raportów z danych.</li>
            <li><a href="{{ url_for('main_routes.superuser_panel') }} " class="btn btn-warning">Panel Zarządzania</a> - dostęp do panelu zarządzania użytkownikami i danymi.</li>
            <li><a href="{{ url_for('main_routes.edit_account') }}" class="btn btn-warning">Edytuj profil</a> - pozwala na edycję danych Twojego konta.</li>
            <li><a href="{{ url_for('main_routes.logout') }}" class="btn btn-warning">Wyloguj</a> - wylogowuje z systemu.</li>
        </ul>
        {% endblock instructions %}
    </div>

    </div>


    <script>
        const searchUserInput = document.getElementById('search-user-input');
        const userList = document.getElementById('user-list');
        const userItems = userList.querySelectorAll('.user-item');

        searchUserInput.addEventListener('input', function() {
            const searchTerm = searchUserInput.value.toLowerCase();

            userItems.forEach(function(item) {
                const userEmail = item.textContent.trim().toLowerCase();
                if (userEmail.includes(searchTerm)) {
                    item.style.display = 'block';
                } else {
                    item.style.display = 'none';
                }
            });
        });
    </script>
{% endblock %}

templates/user_meters.html
{% extends 'base.html' %}
{% block extra_css %}
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='UserList.css')}}">
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='MediaQueries.css')}}">

{% endblock extra_css %}

{% block content %}
<h1>Twoje liczniki</h1>
<ul class="user-list">
    {% for meter in user_meters %}
    <li class="user-item">
        <a href="{{ url_for('main_routes.meter_details', meter_id=meter.id) }}">
            Meter Number: {{ meter.radio_number }} | Name: {{ meter.name }} | Type: {{ meter.type }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/user_summary.html
{% extends 'base.html' %}

{% block content %}
<h2>Podsumowanie Dodanych Użytkowników</h2>
<table class="table">
    <thead>
        <tr>
            <th>Email</th>
            <th>Hasło</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user.email }}</td>
            <td>{{ user.password }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<button id="download-csv" class="btn btn-primary">Pobierz CSV</button>
<button id="print-pdf" class="btn btn-primary">Drukuj PDF</button>
{% endblock %}


<!-- Tutaj dodajemy skrypty JavaScript do pobierania CSV i drukowania PDF -->
<script>
document.getElementById('download-csv').addEventListener('click', function() {
    let csvContent = 'data:text/csv;charset=utf-8,';
    csvContent += 'Email,Hasło\r\n';

    // Dodajemy dane użytkowników
    {{ users | safe }}.forEach(function(user) {
        let row = user.email + ',' + user.password;
        csvContent += row + '\r\n';
    });

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', 'users.csv');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
});

document.getElementById('print-pdf').addEventListener('click', function() {
    window.print();
});

</script>